# Generated by Django 5.1.1 on 2024-09-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='title',
        ),
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='DOCTORS/'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
