# Generated by Django 5.1.1 on 2024-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='DEPARTMENTS/'),
        ),
    ]
